/**
 * Module to provide the ability to view reports that have been generated by users and potentially
 * take action
 */

var fl = require('flux-link');
var db = require('db-filters');

var admin = require('../../admin');

function report_list() {
}

function clear_report(env, after) {
}

function delete_quote(env, after) {
}

// Set up routes
module.exports.init_routes = function(server) {
	var pre_handlers = ['default', 'admin'];
	server.add_route('/admin/report', {fn : report_list(), pre : pre_handlers});
	server.add_route('/admin/report/clear/:id', {fn : clear_report, pre : pre_handlers});
	server.add_route('/admin/report/delete/:id', {fn : delete_quote, pre : pre_handlers});
}
